name: Remove Stale or Waiting Labels
on:
  issue_comment:
    types: [created]
  workflow_dispatch:
jobs:
  remove-labels-on-activity:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@1af3b93b6815bc44a9784bd300feb67ff0d1eeb3 # v6.0.0
      - uses: actions-ecosystem/action-remove-labels@2ce5d41b4b6aa8503e285553f75ed56e0a40bae0 # v1.2.0
        if: contains(github.event.issue.labels.*.name, 'Waiting for Response')
        with:
          labels: |
            Waiting for Response
